# File: /docker-compose.override.yml
# This file is automatically merged with docker-compose.yml in development
version: '3.9'

services:
  backend:
    build:
      target: development
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DEBUG: 'app:*'
    ports:
      - "4000:4000"
      - "9229:9229"  # Node.js debugger port

  frontend:
    build:
      target: development
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development

  worker:
    build:
      target: development
    command: npm run worker:dev
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Development-only services
  postgres-admin:
    image: dpage/pgadmin4:latest
    container_name: social-selling-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@socialselling.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - social-selling-network
    depends_on:
      - postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: social-selling-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - social-selling-network
    depends_on:
      - redis
